name: Deploymenttomainrepo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Update next.config.ts for deployment
      run: |
        sed -i "s/basePath: .*,/basePath: '',/" next.config.ts
        sed -i "s/assetPrefix: .*,/assetPrefix: '',/" next.config.ts

    - name: Build
      run: npm run build

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Deploy to anirudrachoudhury.github.io (date branch)
      uses: peaceiris/actions-gh-pages@v3
      with:
        external_repository: anirudrachoudhury/anirudrachoudhury.github.io
        publish_branch: ${{ steps.date.outputs.date }}
        publish_dir: ./out
        user_name: github-actions[bot]
        user_email: github-actions[bot]@users.noreply.github.com
        personal_token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}